# Generated by Django 5.0.12 on 2025-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_listing_inventory_alter_listing_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='inventories', to='inventory.listing'),
        ),
    ]
