# Generated by Django 5.0.12 on 2025-03-10 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_listings'),
        ('users', '0002_alter_merchant_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liveinventory',
            name='listings',
            field=models.ManyToManyField(related_name='live_inventory', to='inventory.listing'),
        ),
        migrations.AddField(
            model_name='liveinventory',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_inventory', to='users.merchant'),
        ),
    ]
