# Generated by Django 5.0.12 on 2025-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_liveinventory_listing_is_live_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_live', True)), fields=('inventory', 'item'), name='unique_live_listing_per_item_per_merchant'),
        ),
    ]
