# Generated by Django 5.0.12 on 2025-03-10 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_listing_unique_live_listing_per_item_per_merchant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveinventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='liveinventory',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='live_inventory', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
