# Generated by Django 5.0.12 on 2025-03-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='company_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Company Name'),
        ),
    ]
